# ---------------------
# GENERAL CONFIGURATION
# ---------------------

# Version format
version: 1.0.{build}

# Branches to build
branches:
  only:
    - master

skip_tags: true

build:
  verbosity: minimal

  
# -------------------------
# ENVIRONMENT CONFIGURATION
# -------------------------

# VM template
os: Visual Studio 2015

# Environment variables
environment:
  build_scripts_dir: C:\buildScripts
  dependencies_dir: C:\dependencies
  work_dir: C:\work
  staging_dir: C:\work\staging
  temp_dir: C:\temp
  coveralls_repo_token: 
    secure: e3qJzl4/8uKyjdcNKB3HrfAQe46Oq6f2V6HnmNXZZG4oHU8YkVhy4958jmNQDOqJ
  
# Clone directory
clone_folder: C:\work\source

# Init scripts called before cloning
init:
- ps: New-Item "$env:BUILD_SCRIPTS_DIR" -type directory
- ps: New-Item "$env:DEPENDENCIES_DIR" -type directory
- ps: New-Item "$env:STAGING_DIR" -type directory
- ps: New-Item "$env:TEMP_DIR" -type directory
- ps: wget -OutFile "$env:TEMP_DIR\AppVeyorBuildScripts.zip" "https://github.com/afuzzyllama/AppVeyorBuildScripts/archive/master.zip"
- ps: 7z x "$env:TEMP_DIR\AppVeyorBuildScripts.zip" -o"$env:TEMP_DIR"
- ps: Move-Item "$env:TEMP_DIR\AppVeyorBuildScripts-master\*" "$env:BUILD_SCRIPTS_DIR\"
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\getUnity3D.ps1`""
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\getImageMagick.ps1`""
- ps: wget -OutFile "$env:TEMP_DIR\coveralls.net.zip" "https://github.com/csMACnz/coveralls.net/archive/develop.zip"
- ps: 7z x "$env:TEMP_DIR\coveralls.net.zip" -o"$env:TEMP_DIR"
- ps: Move-Item "$env:TEMP_DIR\coveralls.net-develop\*" "$env:DEPENDENCIES_DIR\coveralls.net\" -Force
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\buildCoverallsDotNet.ps1`""

assembly_info:
  patch: true
  file: ProceduralVoxelMesh\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(appveyor_repo_commit)'
 
# -------------------
# BUILD CONFIGURATION
# -------------------
build_script:
- ps: Invoke-Expression "& `"$env:APPVEYOR_BUILD_FOLDER\build.ps1`""
  
after_build:
- ps: Invoke-Expression "& `"$env:APPVEYOR_BUILD_FOLDER\packageBuild.ps1`""
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\zipRelease.ps1`""
  

# ------------------
# TEST CONFIGURATION
# ------------------
before_test:
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\instrumentAssembly.ps1`" '$env:APPVEYOR_BUILD_FOLDER\ProceduralVoxelMesh\bin\Release\ProceduralVoxelMesh.dll'"
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\startPerfmon.ps1`" '$env:APPVEYOR_BUILD_FOLDER\results.coverage'"

test_script:
- ps: Invoke-Expression "& `"$env:APPVEYOR_BUILD_FOLDER\test.ps1`""
  
after_test:
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\shutdownPerfmon.ps1`""
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\convertCoverage.ps1`" '$env:APPVEYOR_BUILD_FOLDER\results.coverage'"

  
# -----------------------
# ARTIFACTS CONFIGURATION
# -----------------------
artifacts:
  - path: C:\work\staging\*.zip
  

# ------------------------
# DEPLOYMENT CONFIGURATION
# ------------------------
deploy:
  provider: GitHub
  auth_token:
    secure: 6rKcqEAzPD0o7RiGVFFaUVXts2nGs3w9SOMTayT3hFQVpc2rCX1rh5Lsg4SqkkrP
  release: ProceduralVoxelMesh-v$(appveyor_build_version)
  description: "Successful CI build of library.  Please consult the [ReadMe](https://github.com/PixelsForGlory/ProceduralVoxelMesh/blob/master/README.md) for implementing this release into your project."
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true 
after_deploy:
- ps: Invoke-Expression "& `"$env:BUILD_SCRIPTS_DIR\coveralls.ps1`" '$env:APPVEYOR_BUILD_FOLDER\results.coveragexml'"


# ---------------------------   
# NOTIFICATIONS CONFIGURATION
# ---------------------------
notifications: 
- provider: Email
  to: 
  - karcieri@gmail.com
  on_build_status_changed: true

