# ---------------------
# GENERAL CONFIGURATION
# ---------------------

# Version format
version: 1.0.{build}

# Branches to build
branches:
  only:
    - master

skip_tags: true

build:
  verbosity: minimal

  
# -------------------------
# ENVIRONMENT CONFIGURATION
# -------------------------

# VM template
os: Visual Studio 2015

# Environment variables
environment:
  build_scripts_dir: C:\buildScripts
  dependencies_dir: C:\dependencies
  work_dir: C:\work
  staging_dir: C:\work\staging
  temp_dir: C:\temp
  coveralls_repo_token: 
    secure: e3qJzl4/8uKyjdcNKB3HrfAQe46Oq6f2V6HnmNXZZG4oHU8YkVhy4958jmNQDOqJ
  
# Clone directory
clone_folder: C:\work\source

# Init scripts called before cloning
init:
  - git clone https://github.com/afuzzyllama/AppVeyorBuildScripts.git $(build_scripts_dir)
  - ps: $(build_scripts_dir)\getUnity3D.ps1
  - ps: $(build_scripts_dir)\getImageMagick.ps1
  - git clone -b develop https://github.com/csMACnz/coveralls.net.git $(dependencies_dir)\coveralls.net
  - ps: $(build_scripts_dir)\buildCoverallsDotNet.ps1

assembly_info:
  patch: true
  file: ProceduralVoxelMesh\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(appveyor_repo_commit)'
 
# -------------------
# BUILD CONFIGURATION
# -------------------
build_script:
  - ps: .\build.ps1
  
after_build:
  - ps: .\packageBuild.ps1 
  - ps: $(build_scripts_dir)\zipRelease.ps1 
  

# ------------------
# TEST CONFIGURATION
# ------------------
before_test:
  - ps: $(build_scripts_dir)\instrumentAssembly.ps1 '$(appveyor_build_folder)\ProceduralVoxelMesh\bin\Release\ProceduralVoxelMesh.dll'
  - ps: $(build_scripts_dir)\startPerfmon.ps1 '$(appveyor_build_folder)\ProceduralVoxelMesh\results.coverage'

test_script:
  - ps: .\test.ps1
  
after_test:
  - ps: $(build_scripts_dir)\shutdownPerfmon.ps1
  - ps: $(build_scripts_dir)\convertCoverage.ps1 '$(appveyor_build_folder)\ProceduralVoxelMesh\results.coverage'

  
# -----------------------
# ARTIFACTS CONFIGURATION
# -----------------------
artifacts:
  - path: $(staging_dir)\*.zip
  

# ------------------------
# DEPLOYMENT CONFIGURATION
# ------------------------
deploy:
  provider: GitHub
  auth_token:
    secure: 6rKcqEAzPD0o7RiGVFFaUVXts2nGs3w9SOMTayT3hFQVpc2rCX1rh5Lsg4SqkkrP
  release: ProceduralVoxelMesh-v$(appveyor_build_version)
  description: "Successful CI build of library.  Please consult the [ReadMe](https://github.com/PixelsForGlory/ProceduralVoxelMesh/blob/master/README.md) for implementing this release into your project."
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true 
after_deploy:
  - ps: $(build_scripts_dir)\coveralls.ps1 '$(appveyor_build_folder)\ProceduralVoxelMesh\results.coveragexml'


# ---------------------------   
# NOTIFICATIONS CONFIGURATION
# ---------------------------
notifications: 
- provider: Email
  to: 
  - karcieri@gmail.com
  on_build_status_changed: true

